// npm install --no-save playwright; npx playwright install chromium
// Start `npm start` in a separate terminal. BROWSER_CHANNEL=msedge uses installed Edge.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const base=process.env.TEST_URL||'http://127.0.0.1:4173/wedding/';
const out=process.env.TEST_OUTPUT_DIR||path.resolve('test-results');fs.mkdirSync(out,{recursive:true});
const results=[];
const state=page=>page.evaluate(async()=>{const {game}=await import('./js/app.js');return { ...game.state,auto:game.auto,hidden:game.hidden,pendingReward:game.pendingReward,claimed:game.claimed,galleryOpen:game.galleryOpen};});
const check=(name,value)=>{assert(value,name);results.push(name);console.log('PASS',name);};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))errors.push(`${r.status()} ${r.url()}`);});
 await page.goto(base);await page.screenshot({path:path.join(out,'01-title-mobile.png'),fullPage:true});
 check('Autoplay preference on; 15 configured photos',await page.evaluate(async()=>{const {game}=await import('./js/app.js');const {CONFIG}=await import('./js/config.js');return game.sound&&CONFIG.photos.length===15;}));
 const dismiss=async()=>{for(let i=0;i<12&&await page.locator('#dialogue').isVisible();i++){await page.locator('#dialogue').click();await page.waitForTimeout(70);}assert(!await page.locator('#dialogue').isVisible());};
 const move=async(id)=>{await page.locator(`[data-point="${id}"]`).click();await page.waitForFunction(()=>!document.getElementById('action').disabled,{},{timeout:15000});};
 const action=()=>page.locator('#action').click();
 const treasure=async(key)=>{check('Reward unlocked: '+key,(await state(page)).pendingReward===key);await page.locator('.treasure-button').click();await page.locator('#photo-gallery').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('gallery-image').naturalWidth>0);const before=await state(page);await page.keyboard.press('ArrowRight');check('Photo arrow advances without moving game: '+key,(await page.locator('#photo-count').textContent()).includes('02'));await page.keyboard.press('ArrowLeft');const after=await state(page);check('Game paused during photo viewing: '+key,JSON.stringify(before.player)===JSON.stringify(after.player)&&before.chapter===after.chapter);if(key==='meet')await page.waitForTimeout(600);if(key==='meet')await page.screenshot({path:path.join(out,'03-treasure-photo.png'),fullPage:true});await page.locator('#gallery-continue').click();await page.waitForFunction(()=>!document.getElementById('photo-gallery').open);};
 await action();await dismiss();check('Chapter 1 starts alone',!(await state(page)).joined);
 // Keyboard movement and touch movement both operate the real engine.
 await page.locator('#canvas').focus();const start=(await state(page)).player.x;await page.keyboard.down('ArrowRight');await page.waitForTimeout(300);await page.keyboard.up('ArrowRight');check('Arrow-key movement',(await state(page)).player.x>start+8);
 await move('path');await action();check('Chapter 2 entered',(await state(page)).chapter===2);await move('meet');await action();await dismiss();check('Companion joins after greeting',(await state(page)).joined);await treasure('meet');await action();
 check('Chapter 3 starts with zero hearts',(await state(page)).hearts.length===0);await move('cafe');await action();await dismiss();await treasure('cafe');
 await page.locator('[data-point="flowers"]').click();await page.waitForTimeout(900);let walking=await state(page);check('Companion follows player',walking.joined&&Math.hypot(walking.player.x-walking.partner.x,walking.player.y-walking.partner.y)<38);await page.waitForFunction(()=>!document.getElementById('action').disabled,{},{timeout:15000});await action();await dismiss();await treasure('flowers');
 await move('photo');await action();await dismiss();await treasure('photo');check('All 3 memories collected',(await state(page)).hearts.length===3);await page.screenshot({path:path.join(out,'04-memories.png'),fullPage:true});
 await move('next');await action();check('Chapter 4 entered',(await state(page)).chapter===4);await move('promise');await action();await dismiss();check('Ring offered',(await state(page)).proposalStep===1);await action();await dismiss();await treasure('promise');await action();
 check('Chapter 5 wedding outfits active',(await state(page)).chapter===5);await page.screenshot({path:path.join(out,'05-wedding.png'),fullPage:true});await move('aisle');await action();await dismiss();await action();check('Full manual journey reaches invitation',await page.locator('#invitation').isVisible());
 await page.locator('#copy-link').click();check('Link copies current subpath URL',await page.evaluate(()=>navigator.clipboard.readText())===base);
 check('Venue telephone link correct',await page.locator('a[href^="tel:"]').first().getAttribute('href')==='tel:0221118888');check('Two map service links',await page.locator('a[href^="https://map.naver.com/"],a[href^="https://map.kakao.com/"]').count()===2);
 check('Calendar marks Saturday 19',await page.locator('.wedding-day').textContent()==='19'&&await page.locator('.wedding-day').evaluate(e=>e.cellIndex)===6);
 check('D-Day changes at Korean midnight',await page.evaluate(async()=>{const {daysUntil}=await import('./js/invitation.js');return daysUntil(new Date('2026-12-18T14:59:59Z'))===1&&daysUntil(new Date('2026-12-18T15:00:00Z'))===0&&daysUntil(new Date('2026-12-19T15:00:00Z'))===-1;}));
 await page.locator('#view-album').click();check('Full album includes all 15 images',(await page.locator('#photo-count').textContent()).includes('15'));await page.locator('#close-gallery').click();
 await page.locator('#replay').click();let reset=await state(page);check('Replay resets positions, hearts, treasures and automatic mode',reset.title&&reset.hearts.length===0&&reset.claimed.length===0&&!reset.joined&&!reset.auto&&reset.player.x===108);
 await action();await dismiss();await page.locator('#auto').click();await page.waitForTimeout(800);await page.locator('#auto').click();let paused=await state(page);await page.waitForTimeout(650);let stopped=await state(page);check('Auto off cancels movement with no stale commands',!stopped.auto&&Math.abs(stopped.player.x-paused.player.x)<1);
 await page.locator('#skip').click();await page.locator('#replay').click();
 for(const size of [{width:320,height:568},{width:360,height:640},{width:390,height:844},{width:1440,height:1000}]){await page.setViewportSize(size);check(`Viewport ${size.width}×${size.height} no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(`Viewport ${size.width}×${size.height} start and skip visible`,await page.locator('#action').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight)&&await page.locator('#skip').evaluate(e=>e.getBoundingClientRect().top>=0));if(size.width===320)await page.screenshot({path:path.join(out,'02-small-screen.png'),fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#action').click();check('Reduced motion is respected',(await state(page)).reduced);await dismiss();const y=await page.evaluate(()=>scrollY);const cdp=await context.newCDPSession(page);const box=await page.locator('#canvas').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+120,y:box.y+130}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+120,y:box.y+80}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('Canvas touch does not scroll page',await page.evaluate(()=>scrollY)===y);
 await page.waitForTimeout(700);await page.locator('#skip').click();await page.locator('#invitation').waitFor({state:'visible'});await page.locator('#replay').click();await page.emulateMedia({reducedMotion:'no-preference'});
 // Complete, unaccelerated auto journey; check skip availability at each actual chapter.
 const seen=new Set();await page.locator('#auto').click();const begun=Date.now();
 while(Date.now()-begun<160000){const s=await state(page);if(s.chapter&&!seen.has(s.chapter)){seen.add(s.chapter);check('Skip visible in chapter '+s.chapter,await page.locator('#skip').isVisible());}if(s.hidden)break;await page.waitForTimeout(1000);}
 check('Full automatic journey including all five treasure albums completes',(await state(page)).hidden&&seen.size===5);check('All 15 photos rewarded in automatic journey',(await state(page)).claimed.length===5);
 check('No browser errors or missing subpath resources',errors.length===0);
 // Exercise the actual skip action from every chapter in independent, quickly staged instances.
 for(let chapter=1;chapter<=5;chapter++){await page.locator('#replay').click();await page.evaluate(async ch=>{const {game}=await import('./js/app.js');game.enter(ch);},chapter);await page.locator('#skip').click();check('Skip action works in chapter '+chapter,await page.locator('#invitation').isVisible());}
 await page.locator('#replay').click();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(out,'06-desktop.png'),fullPage:true});
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:results.length,checks:results,errors,autoSeconds:Math.round((Date.now()-begun)/1000)},null,2));
 await browser.close();console.log(`COMPLETE: ${results.length} checks passed.`);
})().catch(e=>{console.error(e);process.exit(1);});
